"""AI Prompts module for travel planning."""

from .intent_extraction import (
    INTENT_EXTRACTION_PROMPT,
    QUESTION_TEMPLATES,
    PROGRESS_MESSAGES,
)
from .followup_handler import (
    FOLLOWUP_TYPE_DETECTION_PROMPT,
    MODIFICATION_DETECTION_PROMPT,
    SUGGESTION_EXTRACTION_PROMPT,
    STATIC_SUGGESTIONS,
    COMPANION_SUGGESTION_FILTERS,
)

__all__ = [
    "INTENT_EXTRACTION_PROMPT",
    "QUESTION_TEMPLATES",
    "PROGRESS_MESSAGES",
    "FOLLOWUP_TYPE_DETECTION_PROMPT",
    "MODIFICATION_DETECTION_PROMPT",
    "SUGGESTION_EXTRACTION_PROMPT",
    "STATIC_SUGGESTIONS",
    "COMPANION_SUGGESTION_FILTERS",
]
